import React, { useEffect, useState, useCallback } from 'react';
import { View, FlatList, StyleSheet, Alert } from 'react-native';
import { Text, Card, Chip, ActivityIndicator } from 'react-native-paper';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { AdminStackParamList, Invoice } from '../../types';
import { getInvoicesByFilter } from '../../services/invoices';

type Props = NativeStackScreenProps<AdminStackParamList, 'InvoiceList'>;

const STATUS_COLORS: Record<string, string> = {
  pending: '#FFF9C4',
  paid: '#C8E6C9',
  overdue: '#FFCDD2',
};

function fmt(amount: number) {
  return `$${amount.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

export default function InvoiceListScreen({ route }: Props) {
  const { filter, title } = route.params;
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [loading, setLoading] = useState(true);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const data = await getInvoicesByFilter(filter);
      data.sort((a, b) => (b.invoiceDate?.getTime() ?? 0) - (a.invoiceDate?.getTime() ?? 0));
      setInvoices(data);
    } catch {
      Alert.alert('Error', 'Failed to load invoices.');
    } finally {
      setLoading(false);
    }
  }, [filter]);

  useEffect(() => { load(); }, [load]);

  const totalAmount = invoices.reduce((s, i) => s + i.amount, 0);

  if (loading) return <ActivityIndicator style={styles.center} />;

  return (
    <View style={styles.container}>
      {invoices.length > 0 && (
        <View style={styles.summary}>
          <Text style={styles.summaryText}>
            {invoices.length} {invoices.length === 1 ? 'invoice' : 'invoices'} · {fmt(totalAmount)}
          </Text>
        </View>
      )}
      <FlatList
        data={invoices}
        keyExtractor={(item) => item.id}
        contentContainerStyle={styles.list}
        renderItem={({ item }) => (
          <Card style={styles.card}>
            <Card.Content>
              <View style={styles.row}>
                <Text variant="titleSmall" style={styles.memberName}>{item.memberName}</Text>
                <Chip
                  compact
                  mode="flat"
                  style={{ backgroundColor: STATUS_COLORS[item.status] }}
                  textStyle={{ fontSize: 10 }}
                >
                  {item.status.toUpperCase()}
                </Chip>
              </View>
              <View style={styles.row}>
                <Text variant="bodySmall" style={styles.period}>{item.period}</Text>
                <Text variant="bodyMedium" style={styles.amount}>{fmt(item.amount)}</Text>
              </View>
              {item.pastDueAmount > 0 && (
                <Text variant="bodySmall" style={styles.pastDue}>
                  Includes {fmt(item.pastDueAmount)} past due
                </Text>
              )}
              <Text variant="bodySmall" style={styles.meta}>
                Due: {item.dueDate?.toLocaleDateString()}
              </Text>
              {item.generatedBy ? (
                <Text variant="bodySmall" style={styles.meta}>
                  Generated by: {item.generatedBy}
                </Text>
              ) : null}
              {item.status === 'paid' && item.paidDate && (
                <>
                  <Text variant="bodySmall" style={styles.paidDate}>
                    Paid: {item.paidDate.toLocaleDateString()} via {item.paymentMethod}
                  </Text>
                  {item.processedBy ? (
                    <Text variant="bodySmall" style={styles.paidDate}>
                      Processed by: {item.processedBy}
                    </Text>
                  ) : null}
                </>
              )}
            </Card.Content>
          </Card>
        )}
        refreshing={loading}
        onRefresh={load}
        ListEmptyComponent={
          <View style={styles.emptyContainer}>
            <Text style={styles.empty}>No invoices found.</Text>
          </View>
        }
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F4F6F9' },
  center: { flex: 1 },
  summary: {
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  summaryText: { fontSize: 13, color: '#546E7A', fontWeight: '600' },
  list: { padding: 12, paddingBottom: 24 },
  card: { marginBottom: 8, borderRadius: 10 },
  row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 },
  memberName: { fontWeight: '600', flex: 1, marginRight: 8 },
  period: { color: '#78909C' },
  amount: { fontWeight: '700', color: '#263238' },
  pastDue: { color: '#C62828', marginBottom: 2 },
  meta: { color: '#90A4AE', marginTop: 2 },
  paidDate: { color: '#2E7D32', marginTop: 2 },
  emptyContainer: { flex: 1, alignItems: 'center', marginTop: 60 },
  empty: { color: '#90A4AE', fontSize: 15 },
});
